Repository voiceflow/api-sdk, pull requests merged in 2021-02, with the labels that each got.

#48 feat: prototype data update endpoint (CORE-5147)
  src/models/version.ts
  src/resources/version.ts
  tests/resources/version.unit.ts
Labels: ready to merge

#49 feat: api keys (CORE-5131)
  src/client.ts
  src/models/apiKey.ts
  src/models/index.ts
  src/models/shared.ts
  src/resources/apiKey.ts
  src/resources/index.ts
  tests/client.unit.ts
Labels: ready for review

#50 feat: API Key Verification (CORE-5221)
  src/resources/user.ts
  tests/client.unit.ts
  tests/resources/user.unit.ts
Labels: in review
